### ISSUE TITLE
Continue the developing of the F-Droid version

### ISSUE THREAD

**Issue by AlphaOmega3** [j4velin/SystemAppMover#12]

**Comment by j4velin** [comment]
There is no separate F-Droid version

**Comment by AlphaOmega3** [comment]
I'm sorry, but I saw it on the Play Store is version 1.7.1 (20/06/2016), while on the F-Droid is stopped to version 1.7 (11/20/2015) .. I thought were 2 versions different. 

Updates of the F-Droid, please.

**Comment by j4velin** [comment]
Building and updating the app for F-Droid is up to the F-Droid guys. Apparently, the didn't build the latest version because they don't support the used build tools version: https://f-droid.org/wiki/page/de.j4velin.systemappmover
