### ISSUE TITLE
Request permission to create a new logo

### ISSUE THREAD

**Issue by jaldesign93** [j4velin/SystemAppMover#15]
Hey bro we would like to ask your permission to create a new logo for your application, if logo finished we will give logo link here...

**Comment by jaldesign93** [comment]
hey bro i made new logo for you, you can check detail here https://utopian.io/utopian-io/@jaldesign/new-logo-icon-proposal-for-app-mover

**Comment by j4velin** [comment]
Thanks, looks good!

jaldesign93 <notifications@github.com> schrieb am Mo., 26. Feb. 2018 um
08:49 Uhr:

**Comment by jaldesign93** [comment]
wow thanks again, i'm so glad to hear that.

**Comment by j4velin** [comment]
Integrated in commit https://github.com/j4velin/SystemAppMover/commit/5ef2ec8b18ece974f8b04e855db764c05b594006
