### ISSUE TITLE
4.4.4 problems?

### ISSUE THREAD

**Issue by 101111** [j4velin/SystemAppMover#7]
Doesn't work in 4.4.4? ...can't move any APP Form sytem to normal.

**Comment by famo** [comment]
Works fine here on 4.4.4.

**Comment by neofutur** [comment]
main feature works on 4.4.4 here , but : 

* reboot offer have no effect if I say yes
* asks for superuser rights everytime i change something and come back to the list, even if I already gave permissions for 10 mins
* still have to manually move every app to sd after i changed the system status.
